# Generated by Django 4.0.4 on 2022-06-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enter_staff', '0005_alter_control_informationcountdown_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Control',
            new_name='ControlCountdown',
        ),
    ]
