# Generated by Django 4.0.4 on 2022-06-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter_staff', '0008_alter_controlcountdown_photocountdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcountdown',
            name='photoCountdown',
            field=models.CharField(choices=[('0', 'Fast (not recommended)'), ('1', '0 Giây'), ('2', '1 Giây'), ('3', '2 Giây'), ('4', '3 Giây')], default='3', max_length=2),
        ),
    ]
